package SRM490_495;
import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class InterestingParty
{
	public int bestInvitation(String[] first, String[] second)
	{
		
	    Map<String, Integer> map = new HashMap<String, Integer>();
	    
	    for (int i = 0; i < first.length; i++) {
	        {
	        int count = 0;
	        if (map.containsKey(first[i])) {
	            count = map.get(first[i]);
	        }
	        count ++;
	        map.put(first[i], count);
	        }
	        {
	        int count = 0;
	        if (map.containsKey(second[i])) {
	            count = map.get(second[i]);
	        }
	        count ++;
	        map.put(second[i], count);
	        }
	    }
	    
	    int ret = 0;
	    for (int count : map.values()) {
	        ret = Math.max(ret, count);
	    }
	    return ret;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit-pf 2.3.0
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, String[] p1, boolean hasAnswer, int p2) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p1.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p1[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		InterestingParty obj;
		int answer;
		obj = new InterestingParty();
		long startTime = System.currentTimeMillis();
		answer = obj.bestInvitation(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			res = answer == p2;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
			if (hasAnswer) {
				System.out.println("Desired answer:");
				System.out.println("\t" + p2);
			}
			System.out.println("Your answer:");
			System.out.println("\t" + answer);
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		boolean disabled;
		boolean tests_disabled;
		all_right = true;
		tests_disabled = false;
		
		String[] p0;
		String[] p1;
		int p2;
		
		// ----- test 0 -----
		disabled = false;
		p0 = new String[]{"fishing","gardening","swimming","fishing"};
		p1 = new String[]{"hunting","fishing","fishing","biting"};
		p2 = 4;
		all_right = (disabled || KawigiEdit_RunTest(0, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 1 -----
		disabled = false;
		p0 = new String[]{"variety","diversity","loquacity","courtesy"};
		p1 = new String[]{"talking","speaking","discussion","meeting"};
		p2 = 1;
		all_right = (disabled || KawigiEdit_RunTest(1, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 2 -----
		disabled = false;
		p0 = new String[]{"snakes","programming","cobra","monty"};
		p1 = new String[]{"python","python","anaconda","python"};
		p2 = 3;
		all_right = (disabled || KawigiEdit_RunTest(2, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 3 -----
		disabled = false;
		p0 = new String[]{"t","o","p","c","o","d","e","r","s","i","n","g","l","e","r","o","u","n","d","m","a","t","c","h","f","o","u","r","n","i"};
		p1 = new String[]{"n","e","f","o","u","r","j","a","n","u","a","r","y","t","w","e","n","t","y","t","w","o","s","a","t","u","r","d","a","y"};
		p2 = 6;
		all_right = (disabled || KawigiEdit_RunTest(3, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		if (all_right) {
			if (tests_disabled) {
				System.out.println("You're a stud (but some test cases were disabled)!");
			} else {
				System.out.println("You're a stud (at least on given cases)!");
			}
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// Mr. White is a very versatile person - absolutely everything is interesting to him. Perhaps this is why he has many friends. Quite unfortunately, however, none of his friends are versatile at all. Each of them is interested only in two topics and refuses to talk about anything else. Therefore, each time Mr. White organizes a party, it's a big problem for him to decide whom to invite so that the party is interesting to everybody. 
	// Now that Mr. White has a lot of experience in organizing parties, he knows for sure that a party will be interesting if and only if there's a topic interesting to each of the invited friends.
	// 
	// You will be given String[]s first and second. The i-th friend of Mr. White is interested in topics first[i] and second[i]. 
	// Return the largest number of friends that Mr. White can invite to his party so that the party will be interesting.
	// 
	// DEFINITION
	// Class:InterestingParty
	// Method:bestInvitation
	// Parameters:String[], String[]
	// Returns:int
	// Method signature:int bestInvitation(String[] first, String[] second)
	// 
	// 
	// CONSTRAINTS
	// -first will contain between 1 and 50 elements, inclusive.
	// -second will contain the same number of elements as first.
	// -Each element of first and second will contain between 1 and 15 characters, inclusive.
	// -Each character in first and second will be a lowercase letter ('a'-'z').
	// -For each valid i, first[i] will not be the same as second[i].
	// 
	// 
	// EXAMPLES
	// 
	// 0)
	// {"fishing", "gardening", "swimming", "fishing"}
	// {"hunting", "fishing", "fishing", "biting"}
	// 
	// Returns: 4
	// 
	// This is a very easy case since everybody is interested in "fishing".
	// 
	// 1)
	// {"variety", "diversity", "loquacity", "courtesy"}
	// {"talking", "speaking", "discussion", "meeting"}
	// 
	// Returns: 1
	// 
	// Despite being interested in "talking", "speaking", "meeting" and so on, these people have nothing to talk about with each other.
	// 
	// 2)
	// {"snakes", "programming", "cobra", "monty"}
	// {"python", "python", "anaconda", "python"}
	// 
	// Returns: 3
	// 
	// Mr. White can invite friends 0, 1, 3 (0-based) and they will have an interesting evening talking about "python" (or at least Mr. White thinks so).
	// 
	// 3)
	// {"t", "o", "p", "c", "o", "d", "e", "r", "s", "i", "n", "g", "l", "e", "r",
	//  "o", "u", "n", "d", "m", "a", "t", "c", "h", "f", "o", "u", "r", "n", "i"}
	// {"n", "e", "f", "o", "u", "r", "j", "a", "n", "u", "a", "r", "y", "t", "w", 
	//  "e", "n", "t", "y", "t", "w", "o", "s", "a", "t", "u", "r", "d", "a", "y"}
	// 
	// Returns: 6
	// 
	// 
	// 
	// END KAWIGIEDIT TESTING
}

//Powered by KawigiEdit-pf 2.3.0!
