package old;
import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class CatAndRat
{
	public double getTime(int R, int T, int Vrat, int Vcat)
	{
		
	    if (Vrat >= Vcat) {
	        return -1;
	    }
	    
	    double startMaxLength = Math.min(R * Math.PI, T * Vrat);
	    
	    return startMaxLength / (Vcat - Vrat);
	    
	    
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit-pf 2.3.0
	private static boolean KawigiEdit_RunTest(int testNum, int p0, int p1, int p2, int p3, boolean hasAnswer, double p4) {
		System.out.print("Test " + testNum + ": [" + p0 + "," + p1 + "," + p2 + "," + p3);
		System.out.println("]");
		CatAndRat obj;
		double answer;
		obj = new CatAndRat();
		long startTime = System.currentTimeMillis();
		answer = obj.getTime(p0, p1, p2, p3);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			res = answer == answer && Math.abs(p4 - answer) <= 1e-9 * Math.max(1.0, Math.abs(p4));
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
			if (hasAnswer) {
				System.out.println("Desired answer:");
				System.out.println("\t" + p4);
			}
			System.out.println("Your answer:");
			System.out.println("\t" + answer);
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		boolean disabled;
		boolean tests_disabled;
		all_right = true;
		tests_disabled = false;
		
		int p0;
		int p1;
		int p2;
		int p3;
		double p4;
		
		// ----- test 0 -----
		disabled = false;
		p0 = 10;
		p1 = 1;
		p2 = 1;
		p3 = 1;
		p4 = -1.0D;
		all_right = (disabled || KawigiEdit_RunTest(0, p0, p1, p2, p3, true, p4) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 1 -----
		disabled = false;
		p0 = 10;
		p1 = 1;
		p2 = 1;
		p3 = 2;
		p4 = 1.0D;
		all_right = (disabled || KawigiEdit_RunTest(1, p0, p1, p2, p3, true, p4) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 2 -----
		disabled = false;
		p0 = 10;
		p1 = 1;
		p2 = 2;
		p3 = 1;
		p4 = -1.0D;
		all_right = (disabled || KawigiEdit_RunTest(2, p0, p1, p2, p3, true, p4) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 3 -----
		disabled = false;
		p0 = 1000;
		p1 = 1000;
		p2 = 1;
		p3 = 1000;
		p4 = 1.001001001001001D;
		all_right = (disabled || KawigiEdit_RunTest(3, p0, p1, p2, p3, true, p4) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 4 -----
		disabled = false;
		p0 = 1;
		p1 = 1000;
		p2 = 1;
		p3 = 2;
		p4 = 3.141592653589793D;
		all_right = (disabled || KawigiEdit_RunTest(4, p0, p1, p2, p3, true, p4) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		if (all_right) {
			if (tests_disabled) {
				System.out.println("You're a stud (but some test cases were disabled)!");
			} else {
				System.out.println("You're a stud (at least on given cases)!");
			}
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// We have a circular tube.
	// At one point the tube has an entrance.
	// 
	// At time 0, a rat enters the tube via the entrance.
	// The rat can move inside the tube in both directions (clockwise and counterclockwise).
	// The rat can change direction in an instant.
	// Its maximum speed is Vrat.
	// 
	// At time T, the cat will enter the tube via the same entrance.
	// The cat can also move in both directions and change its direction instantly.
	// Its maximum speed is Vcat.
	// 
	// For the purpose of this problem, you should imagine the tube as a circle with radius R, and the rat and the cat as points on said circle.
	// 
	// The cat is trying to catch the rat as quickly as possible.
	// The rat is trying not to be caught, and if that is impossible, to be caught as late as possible.
	// At any time (starting at time 0) the cat and the rat know each other's position.
	// Already at time 0 the rat knows the time T.
	// Assume that both the cat and the rat behave optimally.
	// 
	// You are given the ints R, T, Vrat, and Vcat.
	// If the cat will catch the rat successfully, return how much time it'll take the cat to catch the rat.
	// Otherwise, return -1.0.
	// 
	// DEFINITION
	// Class:CatAndRat
	// Method:getTime
	// Parameters:int, int, int, int
	// Returns:double
	// Method signature:double getTime(int R, int T, int Vrat, int Vcat)
	// 
	// 
	// NOTES
	// -The cat and rat cannot leave the tube.
	// -Your return value must have a relative or absolute error less than 1e-9.
	// 
	// 
	// CONSTRAINTS
	// -R, T, Vrat, and Vcat will each be between 1 and 1000, inclusive.
	// 
	// 
	// EXAMPLES
	// 
	// 0)
	// 10
	// 1
	// 1
	// 1
	// 
	// Returns: -1.0
	// 
	// The rat can survive. During the first unit of time it has to run away from the entrance. Then, once the cat enters the tube, the rat can always run in the same direction and with the same speed as the cat.
	// 
	// 1)
	// 10
	// 1
	// 1
	// 2
	// 
	// Returns: 1.0
	// 
	// The cat is now faster than the rat.
	// The best strategy for the rat is to enter the tube and to start running in either direction at its maximum speed.
	// The cat will then enter the tube, run in the same direction as the rat, and catch it in exactly 1 unit of time.
	// 
	// 2)
	// 10
	// 1
	// 2
	// 1
	// 
	// Returns: -1.0
	// 
	// The rat is now faster than the cat. It can survive, for example by using the strategy described in Example 0.
	// 
	// 3)
	// 1000
	// 1000
	// 1
	// 1000
	// 
	// Returns: 1.001001001001001
	// 
	// 
	// 
	// 4)
	// 1
	// 1000
	// 1
	// 2
	// 
	// Returns: 3.141592653589793
	// 
	// 
	// 
	// END KAWIGIEDIT TESTING
}

//Powered by KawigiEdit-pf 2.3.0!
