package old;


import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class EllysLamps
{
	public int getMin(String lamps)
	{
		return 0;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit-pf 2.3.0
	private static boolean KawigiEdit_RunTest(int testNum, String p0, boolean hasAnswer, int p1) {
		System.out.print("Test " + testNum + ": [" + "\"" + p0 + "\"");
		System.out.println("]");
		EllysLamps obj;
		int answer;
		obj = new EllysLamps();
		long startTime = System.currentTimeMillis();
		answer = obj.getMin(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			res = answer == p1;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
			if (hasAnswer) {
				System.out.println("Desired answer:");
				System.out.println("\t" + p1);
			}
			System.out.println("Your answer:");
			System.out.println("\t" + answer);
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		boolean disabled;
		boolean tests_disabled;
		all_right = true;
		tests_disabled = false;
		
		String p0;
		int p1;
		
		// ----- test 0 -----
		disabled = false;
		p0 = "YNNYN";
		p1 = 2;
		all_right = (disabled || KawigiEdit_RunTest(0, p0, true, p1) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 1 -----
		disabled = false;
		p0 = "NNN";
		p1 = 0;
		all_right = (disabled || KawigiEdit_RunTest(1, p0, true, p1) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 2 -----
		disabled = false;
		p0 = "YY";
		p1 = 0;
		all_right = (disabled || KawigiEdit_RunTest(2, p0, true, p1) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 3 -----
		disabled = false;
		p0 = "YNYYYNNNY";
		p1 = 3;
		all_right = (disabled || KawigiEdit_RunTest(3, p0, true, p1) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 4 -----
		disabled = false;
		p0 = "YNYYYYNYNNYYNNNNNNYNYNYNYNNYNYYYNY";
		p1 = 13;
		all_right = (disabled || KawigiEdit_RunTest(4, p0, true, p1) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		if (all_right) {
			if (tests_disabled) {
				System.out.println("You're a stud (but some test cases were disabled)!");
			} else {
				System.out.println("You're a stud (at least on given cases)!");
			}
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// Elly has a row of N lamps, conveniently numbered from 0 to N-1. Some of them are initially lit and the rest are not. She can control the lamps using a controller. On the controller there is a row of N buttons. Clicking the button with index i changes the state of lamp i: it goes off, if it was on, and it goes on if it was off.
	// 
	// Unfortunately the controller has some defects. Each of the buttons correctly changes the state of the corresponding lamp. However, it is possible that some of the buttons also change the state of one or both adjacent lamps as well. This means that pressing the button with index i has the following effects:
	// 
	// The state of lamp i changes.
	// If there is a lamp with index i-1, its state might change.
	// If there is a lamp with index i+1, its state might change.
	// 
	// The girl does not initially know which lamps change their state when each of the buttons is pressed. She knows, however, that every time she clicks a particular button, the same set of lamps will change their states.
	// 
	// Elly wants to reach a configuration in which the number of lamps that are turned on is minimized. Help her determine how many of them will remain lit in the worst possible case. (That is, for the worst possible way how the buttons change the state of the lamps.) She can use each of the buttons as many times as she likes, in any order she likes.
	// 
	// You will be given a String lamps, which gives information about the initial state of the lamps. The i-th character of lamps will be 'Y' if the i-th lamp is lit, and 'N', if it is not. Return the minimal number of lit lamps the girl can get in the worst possible case.
	// 
	// DEFINITION
	// Class:EllysLamps
	// Method:getMin
	// Parameters:String
	// Returns:int
	// Method signature:int getMin(String lamps)
	// 
	// 
	// NOTES
	// -The defects in the switches might not be symmetric. This means that if a lamp with index i happens to change the state of lamp i+1, this does not necessarily mean that the using the switch of lamp i+1 changes the state of lamp i.
	// 
	// 
	// CONSTRAINTS
	// -lamps will contain between 1 and 50 elements, inclusive.
	// -Each element of lamps will be either 'Y' or 'N'.
	// 
	// 
	// EXAMPLES
	// 
	// 0)
	// "YNNYN"
	// 
	// Returns: 2
	// 
	// In this case Elly will only make things worse (or the same) by pressing buttons. For example, suppose that:
	// 
	// buttons 0 and 1 each change the state of both lamps 0 and 1
	// buttons 2 and 3 each change the state of both lamps 2 and 3
	// button 4 only changes the state of lamp 4
	// 
	// In this situation, Elly cannot reach any configuration with fewer than two lit lamps.
	// 
	// 1)
	// "NNN"
	// 
	// Returns: 0
	// 
	// Obviously, with no initially lit lamps, Elly can just sit and relax.
	// 
	// 2)
	// "YY"
	// 
	// Returns: 0
	// 
	// If one of the lamps influences the other one, then Elly can use it and turn both off with one button press. Otherwise, each button changes the state of its lamp only, thus Elly can turn them both off by pressing both buttons.
	// 
	// 3)
	// "YNYYYNNNY"
	// 
	// Returns: 3
	// 
	// 
	// 
	// 4)
	// "YNYYYYNYNNYYNNNNNNYNYNYNYNNYNYYYNY"
	// 
	// Returns: 13
	// 
	// 
	// 
	// END KAWIGIEDIT TESTING
}

//Powered by KawigiEdit-pf 2.3.0!
