import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class AmoebaDivTwo
{
	public int count(String[] table, int K)
	{
	    char[][] space = new char[table.length][];
	    
	    for (int i = 0; i < table.length; i++) {
	        space[i] = table[i].toCharArray();
	    }
	   
	    int ret = 0;
	    for (int i = 0; i < space.length; i++) {
	        int lineCnt = 0;
	        for (int j = 0; j < space[i].length; j++) {
	            if (space[i][j] == 'A') {
	               lineCnt++; 
	            } else {
	               lineCnt = 0; 
	            }
	            
	            if (lineCnt >= K) {
	                ret ++;
	            }
	        }
	    }
	  
	    if ( K > 1) {
            for (int i = 0; i < space[0].length; i++) {
                int lineCnt = 0;
                for (int j = 0; j < space.length; j++) {
                   if (space[j][i] == 'A') {
                       lineCnt++;
                   } else {
                       lineCnt = 0;
                   }
                   
                   if (lineCnt >= K) {
                       ret++;
                   }
                }
            }
	    }
	    return ret;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit-pf 2.3.0
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, int p1, boolean hasAnswer, int p2) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}" + "," + p1);
		System.out.println("]");
		AmoebaDivTwo obj;
		int answer;
		obj = new AmoebaDivTwo();
		long startTime = System.currentTimeMillis();
		answer = obj.count(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			res = answer == p2;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
			if (hasAnswer) {
				System.out.println("Desired answer:");
				System.out.println("\t" + p2);
			}
			System.out.println("Your answer:");
			System.out.println("\t" + answer);
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		boolean disabled;
		boolean tests_disabled;
		all_right = true;
		tests_disabled = false;
		
		String[] p0;
		int p1;
		int p2;
		
		// ----- test 0 -----
		disabled = false;
		p0 = new String[]{"MA"};
		p1 = 2;
		p2 = 0;
		all_right = (disabled || KawigiEdit_RunTest(0, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 1 -----
		disabled = false;
		p0 = new String[]{"AAA","AMA","AAA"};
		p1 = 3;
		p2 = 4;
		all_right = (disabled || KawigiEdit_RunTest(1, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 2 -----
		disabled = false;
		p0 = new String[]{"AA","AA","AA"};
		p1 = 2;
		p2 = 7;
		all_right = (disabled || KawigiEdit_RunTest(2, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 3 -----
		disabled = false;
		p0 = new String[]{"MMM","MMM","MMM"};
		p1 = 1;
		p2 = 0;
		all_right = (disabled || KawigiEdit_RunTest(3, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 4 -----
		disabled = false;
		p0 = new String[]{"AAM","MAM","AAA"};
		p1 = 1;
		p2 = 6;
		all_right = (disabled || KawigiEdit_RunTest(4, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 5 -----
		disabled = false;
		p0 = new String[]{"AAA","AAM","AAA"};
		p1 = 2;
		p2 = 9;
		all_right = (disabled || KawigiEdit_RunTest(5, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		if (all_right) {
			if (tests_disabled) {
				System.out.println("You're a stud (but some test cases were disabled)!");
			} else {
				System.out.println("You're a stud (at least on given cases)!");
			}
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// Little Romeo likes cosmic amoebas a lot.  Recently he received one as a gift from his mother.  He decided to place his amoeba on a rectangular table.  The table is a grid of square 1x1 cells, and each cell is occupied by either matter or antimatter.  The amoeba is a rectangle of size 1xK.  Romeo can place it on the table in any orientation as long as every cell of the table is either completely covered by part of the amoeba or completely uncovered, and no part of the amoeba lies outside of the table.  It is a well-known fact that cosmic amoebas cannot lie on top of matter, so every cell of the table covered by the amoeba must only contain antimatter. 
	// 
	// You are given a String[] table, where the j-th character of the i-th element is 'A' if the cell in row i, column j of the table contains antimatter or 'M' if it contains matter.  Return the number of different ways that Romeo can place the cosmic amoeba on the table.  Two ways are considered different if and only if there is a table cell that is covered in one but not the other.
	// 
	// DEFINITION
	// Class:AmoebaDivTwo
	// Method:count
	// Parameters:String[], int
	// Returns:int
	// Method signature:int count(String[] table, int K)
	// 
	// 
	// CONSTRAINTS
	// -table will contain between 1 and 50 elements, inclusive.
	// -Each element of table will contain between 1 and 50 characters, inclusive.
	// -All elements of table will have the same length.
	// -Each character of each element of table will be either 'A' or 'M'.
	// -K will be between 1 and 50, inclusive.
	// 
	// 
	// EXAMPLES
	// 
	// 0)
	// {"MA"}
	// 2
	// 
	// Returns: 0
	// 
	// The amoeba requires a 1x2 or 2x1 rectangle containing only antimatter, but there is no such space available on the table.
	// 
	// 1)
	// {"AAA",
	//  "AMA",
	//  "AAA"}
	// 3
	// 
	// Returns: 4
	// 
	// 
	// 
	// 2)
	// {"AA",
	//  "AA",
	//  "AA"}
	// 2
	// 
	// Returns: 7
	// 
	// Here are all 7 configurations, where X represents the amoeba:
	// 
	// XX .. .. X. .X .. ..
	// .. XX .. X. .X X. .X
	// .. .. XX .. .. X. .X
	// 
	// 
	// 3)
	// {"MMM",
	//  "MMM",
	//  "MMM"}
	// 1
	// 
	// Returns: 0
	// 
	// There are no cells with antimatter at all.
	// 
	// 4)
	// {"AAM",
	//  "MAM",
	//  "AAA"}
	// 1
	// 
	// Returns: 6
	// 
	// 
	// 
	// 5)
	// {"AAA",
	//  "AAM",
	//  "AAA"}
	// 2
	// 
	// Returns: 9
	// 
	// 
	// 
	// END KAWIGIEDIT TESTING
}

//Powered by KawigiEdit-pf 2.3.0!
